//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class cajatransferencia
    {
        public int Id { get; set; }
        public int OrigenCajaDiarioId { get; set; }
        public int DestinoCajaDiarioId { get; set; }
        public decimal Monto { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Estado { get; set; }
        public bool IndSaldoInicial { get; set; }
    
        public virtual cajadiario cajadiario { get; set; }
        public virtual cajadiario cajadiario1 { get; set; }
    }
}
