//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class matrimonio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public matrimonio()
        {
            this.matrimonio_anexo = new HashSet<matrimonio_anexo>();
        }
    
        public int MatrimonioId { get; set; }
        public string ApellidoNombre { get; set; }
        public string Conyugue { get; set; }
        public System.DateTime Fecha { get; set; }
        public int NroActa { get; set; }
        public int NroLibro { get; set; }
        public string Url { get; set; }
        public Nullable<System.DateTime> Registro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<matrimonio_anexo> matrimonio_anexo { get; set; }
    }
}
