//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class matrimonio_anexo
    {
        public int Matrimonio_AnexoId { get; set; }
        public int MatrimonioId { get; set; }
        public string url { get; set; }
    
        public virtual matrimonio matrimonio { get; set; }
    }
}
