//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class uvw_menus
    {
        public int UsuarioId { get; set; }
        public int RolId { get; set; }
        public int MenuId { get; set; }
        public string Denominacion { get; set; }
        public string Modulo { get; set; }
        public string Icono { get; set; }
        public Nullable<bool> IndPadre { get; set; }
        public Nullable<int> Orden { get; set; }
        public Nullable<int> Referencia { get; set; }
    }
}
